document.write('<ul class="break-column" tabindex=-1>')
	
	document.write('<div class="li"><a href="home.html" tabindex="-1"><img src="images/home.jpg"></a></div>')
	
	document.write('<div class="li"><a href="numbers.html" tabindex="-1">Numbers</a></div>')
  	
  	document.write('<div class="li dropdown">')
    	document.write('<a href="school.html" class="dropbtn" tabindex="-1">School</a>')
		document.write('<div class="dropdown-content">')
		    document.write('<a href="vocab.html">Vocab</a>')
		    document.write('<a href="friends.html">Friends</a>')
		    document.write('<a href="teachers.html">Teachers</a>')
		    document.write('<a href="schedule.html">Schedule</a>')
		    document.write('<a href="calculator.html">Calculator</a>')
		    document.write('<a href="colors.html">Colors</a>')
    	document.write('</div>')
    document.write('</div>')

  	document.write('<div class="li dropdown">')
    	document.write('<a href="social.html" class="dropbtn" tabindex="-1">Social</a>')
		document.write('<div class="dropdown-content">')
		    document.write('<a href="questions.html">Questions</a>')
		    document.write('<a href="comments.html">Comments</a>')
    	document.write('</div>')
    document.write('</div>')

	document.write('<div class="li"><a href="feelings.html" tabindex="-1">Feelings</a></div>')

  	document.write('<div class="li dropdown">')
    	document.write('<a href="want.html" class="dropbtn" tabindex="-1">I want...</a>')
		document.write('<div class="dropdown-content">')
		    document.write('<a href="food.html">Food</a>')
		    document.write('<a href="family.html">Call someone</a>')
    	document.write('</div>')
    document.write('</div>')

  	document.write('<div class="li dropdown">')
    	document.write('<a href="need.html" class="dropbtn" tabindex="-1">I need...</a>')
		document.write('<div class="dropdown-content">')
		    document.write('<a href="break.html">Break</a>')
		    document.write('<a href="not_right.html">Something wrong</a>')
    	document.write('</div>')
    document.write('</div>')

	document.write('<div class="li"><a href="about.html" tabindex="-1">About me</a></div>')

	document.write('<div class="li"><a href="family.html" tabindex="-1">Family</a></div>')

  	document.write('<div class="li dropdown">')
    	document.write('<a href="food.html" class="dropbtn" tabindex="-1">Food</a>')
		document.write('<div class="dropdown-content">')
		    document.write('<a href="breakfast.html">Breakfast</a>')
		    document.write('<a href="snacks.html">Snacks</a>')
		    document.write('<a href="lunch.html">Lunch and dinner</a>')
		    document.write('<a href="fruits.html">Fruits</a>')
		    document.write('<a href="meats.html">Meats</a>')
		    document.write('<a href="vegetables.html">Vegetables</a>')
		    document.write('<a href="condiments.html">Condiments</a>')
		    document.write('<a href="desserts.html">Desserts</a>')
		    document.write('<a href="drinks.html">Drinks</a>')
		    document.write('<a href="cuisine.html">Cuisine</a>')
    	document.write('</div>')
    document.write('</div>')

document.write('</ul>')
